security:
  basic:
    enabled: true         # 开启基于HTTP basic的认证
  user:
    name: user            # 登录用户
    password: 123         # 密码
server:
  port: 7000              # Eureka实例的端口
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/